Repository MEMO-Zi/MEMO-Zi, pull requests merged in 2024-02, with the labels that each got.

#36 [feat] 시작 페이지
  MEMO-Zi/app/src/main/AndroidManifest.xml
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/auth/AuthActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/onboarding/OnboardingActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/onboarding/OnboardingAdapter.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/onboarding/OnboardingDiaryFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/onboarding/OnboardingGreetingFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/onboarding/OnboardingMemoFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/onboarding/OnboardingPopupFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/splash/SplashActivity.kt
  MEMO-Zi/app/src/main/res/drawable-xhdpi/img_app_logo.png
  MEMO-Zi/app/src/main/res/drawable-xxhdpi/img_app_logo.png
  MEMO-Zi/app/src/main/res/drawable/ic_checked_checkbox.xml
  MEMO-Zi/app/src/main/res/drawable/ic_kakao_24.xml
  MEMO-Zi/app/src/main/res/drawable/ic_unchecked_checkbox.xml
  MEMO-Zi/app/src/main/res/drawable/img_app_logo.png
  MEMO-Zi/app/src/main/res/layout/activity_auth.xml
  MEMO-Zi/app/src/main/res/layout/activity_onboarding.xml
  MEMO-Zi/app/src/main/res/layout/activity_splash.xml
  MEMO-Zi/app/src/main/res/layout/fragment_onboarding_diary.xml
  MEMO-Zi/app/src/main/res/layout/fragment_onboarding_greeting.xml
  MEMO-Zi/app/src/main/res/layout/fragment_onboarding_memo.xml
  MEMO-Zi/app/src/main/res/layout/fragment_onboarding_popup.xml
  MEMO-Zi/app/src/main/res/values/dimens.xml
  MEMO-Zi/app/src/main/res/values/strings.xml
  MEMO-Zi/app/src/main/res/values/themes.xml
Labels: feat, 명석😺

#37 [feat] diary camera 기능 구현
  MEMO-Zi/app/src/main/AndroidManifest.xml
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/auth/AuthActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/DiaryActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/DiaryViewModel.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/splash/SplashActivity.kt
  MEMO-Zi/app/src/main/res/layout/activity_diary.xml
  MEMO-Zi/app/src/main/res/layout/fragment_diary_feed.xml
  MEMO-Zi/app/src/main/res/layout/item_diary_calendar.xml
  MEMO-Zi/app/src/main/res/layout/item_diary_feed.xml
Labels: feat, 민우😾

#41 [refactor] textGradation 수정
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/auth/AuthActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/DiaryActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/onboarding/OnboardingDiaryFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/onboarding/OnboardingGreetingFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/onboarding/OnboardingMemoFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/onboarding/OnboardingPopupFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/util/component/LinearGradientSpan.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/util/component/TextGradation.kt
Labels: refactor, 명석😺

#42 [refactor] 메모 화면에 대한 리팩토링
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoEditActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoFeedFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoSearchActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoViewModel.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/adapter/MemoAdapter.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/adapter/MemoCategoryAdapter.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/adapter/MemoListCategoryViewHolder.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/adapter/MemoSearchAdapter.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/adapter/MemoSearchTitleViewHolder.kt
  MEMO-Zi/app/src/main/res/drawable/ic_delete.xml
  MEMO-Zi/app/src/main/res/drawable/ic_x_button.xml
  MEMO-Zi/app/src/main/res/layout/activity_memo.xml
  MEMO-Zi/app/src/main/res/layout/activity_memo_edit.xml
  MEMO-Zi/app/src/main/res/layout/activity_memo_search.xml
  MEMO-Zi/app/src/main/res/layout/bottom_sheet_memo_category_select.xml
  MEMO-Zi/app/src/main/res/layout/fragement_memo_feed.xml
  MEMO-Zi/app/src/main/res/layout/fragment_memo_category_edit.xml
  MEMO-Zi/app/src/main/res/layout/fragment_memo_feed.xml
  MEMO-Zi/app/src/main/res/layout/item_memo_category.xml
  MEMO-Zi/app/src/main/res/layout/item_memo_category_select.xml
  MEMO-Zi/app/src/main/res/values/dimens.xml
  MEMO-Zi/app/src/main/res/values/strings.xml
Labels: refactor, 명석😺
