Repository MEMO-Zi/MEMO-Zi, pull requests merged in 2024-01, with the labels that each got.

#10 Feat/memo
  MEMO-Zi/app/build.gradle
  MEMO-Zi/app/src/main/AndroidManifest.xml
  MEMO-Zi/app/src/main/java/com/memo_zi/data/model/MemoCategory.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/data/model/MemoItem.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoAdapter.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoCategoryAdapter.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoEditActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoListCategoryViewHolder.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoListViewHolder.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoViewModel.kt
  MEMO-Zi/app/src/main/res/drawable/ic_bold.xml
  MEMO-Zi/app/src/main/res/drawable/ic_check.xml
  MEMO-Zi/app/src/main/res/drawable/ic_drop_black_11px.xml
  MEMO-Zi/app/src/main/res/drawable/ic_italic.xml
  MEMO-Zi/app/src/main/res/drawable/ic_memo_add.xml
  MEMO-Zi/app/src/main/res/drawable/ic_orderedlist.xml
  MEMO-Zi/app/src/main/res/drawable/ic_strikethrough.xml
  MEMO-Zi/app/src/main/res/drawable/ic_underline.xml
  MEMO-Zi/app/src/main/res/drawable/img_category.png
  MEMO-Zi/app/src/main/res/drawable/img_category2.jpeg
  MEMO-Zi/app/src/main/res/drawable/shape_memo_background.xml
  MEMO-Zi/app/src/main/res/drawable/shape_memo_category_background.xml
  MEMO-Zi/app/src/main/res/layout/activity_memo.xml
  MEMO-Zi/app/src/main/res/layout/activity_memo_edit.xml
  MEMO-Zi/app/src/main/res/layout/item_memo_category.xml
  MEMO-Zi/app/src/main/res/layout/item_memo_list_all.xml
  MEMO-Zi/app/src/main/res/values/colors.xml
  MEMO-Zi/app/src/main/res/values/dimens.xml
  MEMO-Zi/app/src/main/res/values/strings.xml
Labels: Feat

#16 [refactor] Clean Architecture, Hilt, DataBinding 세팅
  MEMO-Zi/app/build.gradle
  MEMO-Zi/app/src/main/java/com/memo_zi/App.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/data/datasource/DataSourceEx.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/data/datasourceimpl/DataSourceImplEx.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/data/interceptor/AuthInterceptor.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/data/local/ExLocal.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/data/model/remote/request/RequestExDto.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/data/model/remote/response/ResponseExDto.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/data/remote/api/ExApi.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/data/remote/model/ExDataClass.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/data/repositoryimpl/RepositoryImplEx.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/data/service/ServiceEx.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/di/DataSourceModule.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/di/KakaoModule.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/di/RepositoryModule.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/di/RetrofitModule.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/di/ServiceModule.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/di/UseCaseModule.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/domian/entity/EntityEx.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/domian/repository/RepositoryEx.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/domian/usecase/UseCaseEx.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/domian/usecaseimpl/UseCaseImplEx.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/model/ModelEx.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/UiEx.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/repository/ExRepository.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/util/binding/BindingActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/util/binding/BindingAdapter.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/util/binding/BindingFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/util/context/ContextExt.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/util/ext/ContextExt.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/util/ext/ExtensionUtils.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/util/ext/FragmentExt.kt
  MEMO-Zi/build.gradle
Labels: refactor, 민우😾

#13 Feat/memo category
  MEMO-Zi/app/build.gradle
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoCategoryFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoFeedFragment.kt
  MEMO-Zi/app/src/main/res/drawable/bg_category_btn.xml
  MEMO-Zi/app/src/main/res/drawable/bg_categroy_img.xml
  MEMO-Zi/app/src/main/res/drawable/blue_radius.xml
  MEMO-Zi/app/src/main/res/drawable/gray_radius.xml
  MEMO-Zi/app/src/main/res/drawable/ic_edit.xml
  MEMO-Zi/app/src/main/res/layout/activity_memo.xml
  MEMO-Zi/app/src/main/res/layout/fragement_memo_feed.xml
  MEMO-Zi/app/src/main/res/layout/fragment_memo_category_edit.xml
  MEMO-Zi/app/src/main/res/values/colors.xml
  MEMO-Zi/app/src/main/res/values/dimens.xml
  MEMO-Zi/app/src/main/res/values/strings.xml
Labels: feat, 명석😺

#15 Feat/memo delete memo list
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoListViewHolder.kt
  MEMO-Zi/app/src/main/res/drawable/bg_checkbox_off.xml
  MEMO-Zi/app/src/main/res/drawable/bg_round_check_box.xml
  MEMO-Zi/app/src/main/res/layout/frament_memo_category_delete.xml
  MEMO-Zi/app/src/main/res/layout/item_memo_delete.xml
  MEMO-Zi/app/src/main/res/layout/item_memo_list_all.xml
Labels: feat, 명석😺

#20 [refactor] diary 및 Hilt 문제
  .gitignore
  MEMO-Zi/app/build.gradle
  MEMO-Zi/app/src/main/AndroidManifest.xml
  MEMO-Zi/app/src/main/java/com/memo_zi/App.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/data/model/DiaryItem.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/model/DiaryItem.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/model/ModelEx.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/UiEx.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/DiaryActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/DiaryCalendarFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/DiaryFeedFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/DiaryViewModel.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/adapter/CalendarDayAdapter.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/adapter/CalendarMonthAdapter.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/adapter/DiaryAdapter.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/adapter/DiaryListAllViewHolder.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/adapter/DiaryListTitleViewHolder.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoCategoryFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoEditActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/memo/MemoFeedFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/util/DebugTree.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/util/binding/BindingActivity.kt
  MEMO-Zi/app/src/main/res/drawable/ic_calendar_black_20px.xml
  MEMO-Zi/app/src/main/res/drawable/ic_calendar_white_20px.xml
  MEMO-Zi/app/src/main/res/drawable/ic_calender_default_22.xml
  MEMO-Zi/app/src/main/res/drawable/ic_calender_select_22.xml
  MEMO-Zi/app/src/main/res/drawable/ic_feed_black_17px.xml
  MEMO-Zi/app/src/main/res/drawable/ic_feed_default_22.xml
  MEMO-Zi/app/src/main/res/drawable/ic_feed_select_22.xml
  MEMO-Zi/app/src/main/res/drawable/ic_feed_white_17px.xml
  MEMO-Zi/app/src/main/res/drawable/shape_all_radius_4.xml
  MEMO-Zi/app/src/main/res/drawable/shape_all_radius_8.xml
  MEMO-Zi/app/src/main/res/layout/activity_diary.xml
  MEMO-Zi/app/src/main/res/layout/activity_memo.xml
  MEMO-Zi/app/src/main/res/layout/activity_memo_edit.xml
  MEMO-Zi/app/src/main/res/layout/bottom_sheet_calendar.xml
  MEMO-Zi/app/src/main/res/layout/fragement_memo_feed.xml
  MEMO-Zi/app/src/main/res/layout/fragment_diary_calendar.xml
  MEMO-Zi/app/src/main/res/layout/fragment_diary_feed.xml
  MEMO-Zi/app/src/main/res/layout/fragment_memo_category_edit.xml
  MEMO-Zi/app/src/main/res/layout/item_diary_calendar.xml
  MEMO-Zi/app/src/main/res/layout/item_diary_feed.xml
  MEMO-Zi/app/src/main/res/layout/item_diary_list_all.xml
  MEMO-Zi/app/src/main/res/layout/item_memo_list_all.xml
  MEMO-Zi/app/src/main/res/values/dimens.xml
  MEMO-Zi/app/src/main/res/values/strings.xml
  MEMO-Zi/app/src/main/res/values/themes.xml
  MEMO-Zi/build.gradle
  MEMO-Zi/gradle/wrapper/gradle-wrapper.properties
Labels: refactor, 민우😾

#27 [refactor] Diary - 스타일 가이드 대응
  MEMO-Zi/app/build.gradle
  MEMO-Zi/app/src/main/AndroidManifest.xml
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/model/DiaryFeedItem.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/auth/AuthActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/DiaryActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/DiaryViewModel.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/adapter/CalendarDayAdapter.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/adapter/DiaryAdapter.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/adapter/DiaryFeedTitleViewHolder.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/adapter/DiaryFeedViewHolder.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/adapter/DiaryListAllViewHolder.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/adapter/DiaryListTitleViewHolder.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/login/GlobalApplication.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/ui/login/LoginActivity.kt
  MEMO-Zi/app/src/main/res/drawable/background_all_gradation.xml
  MEMO-Zi/app/src/main/res/drawable/ic_line_black_11px.xml
  MEMO-Zi/app/src/main/res/drawable/ic_plus_34.xml
  MEMO-Zi/app/src/main/res/drawable/img_bottom_sheet_rectangle_40.xml
  MEMO-Zi/app/src/main/res/drawable/shape_border_radius_top_24.xml
  MEMO-Zi/app/src/main/res/layout/activity_auth.xml
  MEMO-Zi/app/src/main/res/layout/activity_diary.xml
  MEMO-Zi/app/src/main/res/layout/activity_login.xml
  MEMO-Zi/app/src/main/res/layout/bottom_sheet_calendar.xml
  MEMO-Zi/app/src/main/res/layout/fragment_diary_calendar.xml
  MEMO-Zi/app/src/main/res/layout/fragment_diary_feed.xml
  MEMO-Zi/app/src/main/res/layout/item_calendar_day.xml
  MEMO-Zi/app/src/main/res/layout/item_calendar_month.xml
  MEMO-Zi/app/src/main/res/layout/item_diary_calendar.xml
  MEMO-Zi/app/src/main/res/layout/item_diary_feed.xml
  MEMO-Zi/app/src/main/res/layout/item_diary_feed_title.xml
  MEMO-Zi/app/src/main/res/layout/item_diary_list_title.xml
  MEMO-Zi/app/src/main/res/layout/view_all_top_appbar.xml
  MEMO-Zi/app/src/main/res/menu/diary_tb.xml
  MEMO-Zi/app/src/main/res/menu/memo_tb.xml
  MEMO-Zi/app/src/main/res/values/dimens.xml
  MEMO-Zi/app/src/main/res/values/strings.xml
  MEMO-Zi/app/src/main/res/values/text_appearance.xml
Labels: refactor, 민우😾

#26 [refactor] memo - 스타일 가이드 대응
  MEMO-Zi/app/src/main/AndroidManifest.xml
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/DiaryActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoAdapter.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoCategoryAdapter.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoCategoryFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoEditActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoFeedFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoListCategoryViewHolder.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoListViewHolder.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoViewModel.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/setting/SettingActivity.kt
  MEMO-Zi/app/src/main/res/drawable/ic_bold_24.xml
  MEMO-Zi/app/src/main/res/drawable/ic_cross_20.xml
  MEMO-Zi/app/src/main/res/drawable/ic_drop_11.xml
  MEMO-Zi/app/src/main/res/drawable/ic_edit_14.xml
  MEMO-Zi/app/src/main/res/drawable/ic_empty_check_24.xml
  MEMO-Zi/app/src/main/res/drawable/ic_italic_24.xml
  MEMO-Zi/app/src/main/res/drawable/ic_numbering_24.xml
  MEMO-Zi/app/src/main/res/drawable/ic_strike_24.xml
  MEMO-Zi/app/src/main/res/drawable/ic_underline_24.xml
  MEMO-Zi/app/src/main/res/drawable/img_background_category_defalut.png
  MEMO-Zi/app/src/main/res/layout/activity_memo.xml
  MEMO-Zi/app/src/main/res/layout/activity_memo_edit.xml
  MEMO-Zi/app/src/main/res/layout/activity_setting.xml
  MEMO-Zi/app/src/main/res/layout/fragement_memo_feed.xml
  MEMO-Zi/app/src/main/res/layout/fragment_memo_category_edit.xml
  MEMO-Zi/app/src/main/res/layout/item_memo_list_all.xml
  MEMO-Zi/app/src/main/res/values/colors.xml
  MEMO-Zi/app/src/main/res/values/strings.xml
  MEMO-Zi/app/src/main/res/values/themes.xml
Labels: refactor, 명석😺

#32 [fix] develop 버그해결
  MEMO-Zi/app/src/main/AndroidManifest.xml
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/DiaryActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/DiaryCalendarFragment.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/diary/DiaryViewModel.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoActivity.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoEditActivity.kt
  MEMO-Zi/app/src/main/res/drawable/img_background_category_defalut.png
  MEMO-Zi/app/src/main/res/layout/activity_diary.xml
  MEMO-Zi/app/src/main/res/layout/activity_memo.xml
  MEMO-Zi/app/src/main/res/layout/fragment_category_check.xml
  MEMO-Zi/app/src/main/res/layout/fragment_memo_category_edit.xml
  MEMO-Zi/app/src/main/res/layout/item_memo_category.xml
  MEMO-Zi/app/src/main/res/layout/item_memo_delete.xml
  MEMO-Zi/app/src/main/res/layout/view_all_top_appbar.xml
  MEMO-Zi/app/src/main/res/values/strings.xml
  MEMO-Zi/settings.gradle
Labels: fix, 민우😾, 명석😺

#31 [feat] Snackbar Custom
  MEMO-Zi/app/src/main/java/com/memo_zi/presentation/ui/memo/MemoViewModel.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/util/component/CustomSnackbar.kt
  MEMO-Zi/app/src/main/java/com/memo_zi/util/ext/ContextExt.kt
  MEMO-Zi/app/src/main/res/layout/activity_diary.xml
  MEMO-Zi/app/src/main/res/layout/view_custom_snackbar.xml
Labels: feat, 민우😾
